version: "3.8"

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
      target: base
    ports:
      - ${PORT}:${PORT}
    user: ${USER_ID}:${GROUP_ID}
    command: bash -c 'pnpm dev'
