name: manual-deploy

on:
  repository_dispatch:
    types: [deploy-service]

jobs:
  deploy:
    runs-on: ubuntu-latest

    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}

      - name: Decrypt Data
        run: ENV=${{ github.event.client_payload.environment }} PASSPHRASE=${{ secrets.GPG_PASSPHRASE }} make decrypt-data

      - name: Sync Image To GCR
        run: ENV=${{ github.event.client_payload.environment }} make push-new-image

      - name: Apply Terraform Changes
        run: ENV=${{ github.event.client_payload.environment }} make terraform-apply


